# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a90791fa87af805e8c9d8a444632c01032e04bf5b440f26c6ed7cf2a82e5503e8f9328a23aa0d9dca1ee6d32f50cbe176c4898b91076038325488d2e66b1186d

test:
  secret_key_base: 0bc1b85237a54c75fc0de9c0ee43639879350f90f70d4ecc24191e7418f6d7723924c8f57170e8d4a6e716c518d738983760fe8eb50b9f1bb008017851682edc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
