# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8982acdb298c04ef117d0330c3671e941b08ce8c3f623726c349d7837e69528909bbf0b3013e3667c2da1fbb458dc2b9a46706c4e26cbca3c8c46a9fff8da67d

test:
  secret_key_base: 01c53e518c35ec311c6d7527845fc750f0d567d01b9de59ab4ebbb1cfa8a003a454dbd3f7b78204e82d0b84c8dd9fe7515f3c09a2d096132a695bc01dbb5fb3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
